name: npmjs.com

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: yarn install
        run: yarn install
      - name: Run linter
        run: yarn lint --quiet
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build
      - name: Publish package
        run: yarn publish --new-version ${{ steps.get_version.outputs.version-without-v }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
